"""Step 2 — the memory: an Obsidian-compatible markdown vault.

Plain .md files, no database. Every note gets [[backlinks]] so Obsidian
draws the knowledge graph on its own. Reports the assistant produces are
written back here, which is what future retrieval feeds on.
"""
from __future__ import annotations

import datetime as _dt
import re
from pathlib import Path


def _slug(title: str) -> str:
    slug = re.sub(r"[^\w一-鿿 -]", "", title).strip().replace(" ", "_")
    return slug[:80] or "note"


class Vault:
    def __init__(self, root: Path, *, inbox: str, reports: str, sessions: str):
        self.root = root
        self.inbox = root / inbox
        self.reports = root / reports
        self.sessions = root / sessions
        for d in (self.inbox, self.reports, self.sessions):
            d.mkdir(parents=True, exist_ok=True)

    # -- writing ------------------------------------------------------------
    def write_note(self, title: str, body: str, *, links: list[str] | None = None,
                   folder: Path | None = None) -> Path:
        folder = folder or self.inbox
        stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
        tags = " ".join(f"[[{l}]]" for l in (links or []))
        path = folder / f"{_dt.date.today():%Y%m%d}_{_slug(title)}.md"
        text = f"# {title}\n\n> {stamp} · generated by jarvis-os\n\n{body.strip()}\n"
        if tags:
            text += f"\n---\n{tags}\n"
        path.write_text(text, encoding="utf-8")
        return path

    def write_report(self, title: str, body: str, links: list[str] | None = None) -> Path:
        return self.write_note(title, body, links=links, folder=self.reports)

    def append_session(self, role: str, text: str) -> None:
        """Rolling daily conversation log — the assistant's episodic memory."""
        path = self.sessions / f"{_dt.date.today():%Y-%m-%d}.md"
        stamp = _dt.datetime.now().strftime("%H:%M:%S")
        with path.open("a", encoding="utf-8") as f:
            if path.stat().st_size == 0:
                f.write(f"# Session {_dt.date.today():%Y-%m-%d}\n\n[[Sessions]]\n\n")
            f.write(f"- **{stamp} {role}:** {text.strip()}\n")

    # -- reading ------------------------------------------------------------
    def search(self, query: str, limit: int = 5) -> list[tuple[Path, str]]:
        """Naive full-text search over the vault. Free, local, good enough."""
        terms = [t for t in query.lower().split() if len(t) > 1]
        hits: list[tuple[int, Path, str]] = []
        for md in self.root.rglob("*.md"):
            try:
                text = md.read_text(encoding="utf-8")
            except OSError:
                continue
            lowered = text.lower()
            score = sum(lowered.count(t) for t in terms)
            if score:
                snippet = text[:400].replace("\n", " ")
                hits.append((score, md, snippet))
        hits.sort(key=lambda h: -h[0])
        return [(p, s) for _, p, s in hits[:limit]]

    def stats(self) -> dict:
        notes = list(self.root.rglob("*.md"))
        links = 0
        for md in notes:
            try:
                links += len(re.findall(r"\[\[([^\]]+)\]\]", md.read_text(encoding="utf-8")))
            except OSError:
                pass
        return {"notes": len(notes), "links": links}
